#!/usr/bin/env python3
#
#  process.py
#  
#  Copyright 2026 Gianluca Saba <github@gianlucasaba.it>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

import sys
import csv
import datetime
import argparse

import psycopg

sql_create = '''CREATE TABLE {}(
"ID"	SERIAL PRIMARY KEY,
"COD_LOCALE_PROGETTO"	VARCHAR(255),
"CUP"	VARCHAR(255),
"OC_TITOLO_PROGETTO"	TEXT,
"OC_SINTESI_PROGETTO"	TEXT,
"OC_LINK"	VARCHAR(255),
"OC_COD_CICLO"	DOUBLE PRECISION,
"OC_DESCR_CICLO"	VARCHAR(255),
"OC_COD_TEMA_SINTETICO"	VARCHAR(255),
"OC_TEMA_SINTETICO"	TEXT,
"COD_GRANDE_PROGETTO"	VARCHAR(255),
"DESCRIZIONE_GRANDE_PROGETTO"	VARCHAR(255),
"OC_COD_FONTE"	VARCHAR(255),
"OC_DESCR_FONTE"	VARCHAR(255),
"FONDO_COMUNITARIO"	VARCHAR(255),
"OC_CODICE_PROGRAMMA"	VARCHAR(255),
"OC_DESCRIZIONE_PROGRAMMA"	VARCHAR(255),
"COD_OB_TEMATICO"	VARCHAR(255),
"DESCR_OB_TEMATICO"	TEXT,
"COD_PRIORITA_INVEST"	VARCHAR(255),
"DESCR_PRIORITA_INVEST"	TEXT,
"OC_COD_CATEGORIA_SPESA"	VARCHAR(255),
"OC_DESCR_CATEGORIA_SPESA"	TEXT,
"OC_ARTICOLAZIONE_PROGRAMMA"	VARCHAR(255),
"OC_SUBARTICOLAZIONE_PROGRAMMA"	VARCHAR(255),
"OC_COD_ARTICOLAZ_PROGRAMMA"	VARCHAR(255),
"OC_DESCR_ARTICOLAZ_PROGRAMMA"	TEXT,
"OC_COD_SUBARTICOLAZ_PROGRAMMA"	VARCHAR(255),
"OC_DESCR_SUBARTICOLAZ_PROGRAMMA"	TEXT,
"COD_STRUMENTO"	VARCHAR(255),
"DESCR_STRUMENTO"	TEXT,
"DESCR_TIPO_STRUMENTO"	TEXT,
"CUP_COD_NATURA"	VARCHAR(255),
"CUP_DESCR_NATURA"	VARCHAR(255),
"CUP_COD_TIPOLOGIA"	VARCHAR(255),
"CUP_DESCR_TIPOLOGIA"	VARCHAR(255),
"CUP_COD_SETTORE"	VARCHAR(255),
"CUP_DESCR_SETTORE"	VARCHAR(255),
"CUP_COD_SOTTOSETTORE"	VARCHAR(255),
"CUP_DESCR_SOTTOSETTORE"	TEXT,
"CUP_COD_CATEGORIA"	VARCHAR(255),
"CUP_DESCR_CATEGORIA"	TEXT,
"COD_ATECO"	VARCHAR(255),
"DESCRIZIONE_ATECO"	VARCHAR(255),
"OC_COD_TIPO_AIUTO"	VARCHAR(255),
"OC_DESCR_TIPO_AIUTO"	VARCHAR(255),
"COD_REGIONE"	VARCHAR(255),
"DEN_REGIONE"	VARCHAR(255),
"COD_PROVINCIA"	TEXT,
"DEN_PROVINCIA"	TEXT,
"COD_COMUNE"	TEXT,
"DEN_COMUNE"	TEXT,
"OC_MACROAREA"	VARCHAR(255),
"OC_COD_SLL"	DOUBLE PRECISION,
"OC_DENOMINAZIONE_SLL"	VARCHAR(255),
"FINANZ_UE"	DOUBLE PRECISION,
"FINANZ_UE_FESR"	DOUBLE PRECISION,
"FINANZ_UE_FSE"	DOUBLE PRECISION,
"FINANZ_UE_FEASR"	DOUBLE PRECISION,
"FINANZ_UE_FEAMP"	DOUBLE PRECISION,
"FINANZ_UE_IOG"	DOUBLE PRECISION,
"FINANZ_STATO_FONDO_DI_ROTAZIONE"	DOUBLE PRECISION,
"FINANZ_STATO_FSC"	DOUBLE PRECISION,
"FINANZ_STATO_PAC"	DOUBLE PRECISION,
"FINANZ_STATO_COMPLETAMENTI"	DOUBLE PRECISION,
"FINANZ_STATO_ALTRI_PROVVEDIMENTI"	DOUBLE PRECISION,
"FINANZ_REGIONE"	DOUBLE PRECISION,
"FINANZ_PROVINCIA"	DOUBLE PRECISION,
"FINANZ_COMUNE"	DOUBLE PRECISION,
"FINANZ_RISORSE_LIBERATE"	DOUBLE PRECISION,
"FINANZ_ALTRO_PUBBLICO"	DOUBLE PRECISION,
"FINANZ_STATO_ESTERO"	DOUBLE PRECISION,
"FINANZ_PRIVATO"	DOUBLE PRECISION,
"FINANZ_DA_REPERIRE"	DOUBLE PRECISION,
"FINANZ_TOTALE_PUBBLICO"	DOUBLE PRECISION,
"ECONOMIE_TOTALI"	DOUBLE PRECISION,
"ECONOMIE_TOTALI_PUBBLICHE"	DOUBLE PRECISION,
"OC_FINANZ_UE_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_UE_FESR_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_UE_FSE_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_UE_FEASR_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_UE_FEAMP_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_UE_IOG_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_STATO_FONDO_ROT_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_STATO_FSC_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_STATO_PAC_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_STATO_COMPL_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_STATO_ALTRI_PROV_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_REGIONE_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_PROVINCIA_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_COMUNE_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_RISORSE_LIBERATE_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_ALTRO_PUBBLICO_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_STATO_ESTERO_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_PRIVATO_NETTO"	DOUBLE PRECISION,
"OC_FINANZ_TOT_PUB_NETTO"	DOUBLE PRECISION,
"OC_COSTO_COESIONE"	DOUBLE PRECISION,
"IMPEGNI"	DOUBLE PRECISION,
"OC_IMPEGNI_GIURID_VINCOLANTI"	DOUBLE PRECISION,
"OC_IMPEGNI_TRASFERIMENTI"	DOUBLE PRECISION,
"OC_IMPEGNI_COESIONE"	DOUBLE PRECISION,
"TOT_PAGAMENTI"	DOUBLE PRECISION,
"OC_TOT_PAGAMENTI_BENEFICIARI"	DOUBLE PRECISION,
"OC_TOT_PAGAMENTI_TRASFERIMENTI"	DOUBLE PRECISION,
"COSTO_REALIZZATO"	DOUBLE PRECISION,
"COSTO_RENDICONTABILE_UE"	DOUBLE PRECISION,
"OC_TOT_PAGAMENTI_RENDICONTAB_UE"	DOUBLE PRECISION,
"OC_TOT_PAGAMENTI_FSC"	DOUBLE PRECISION,
"OC_TOT_PAGAMENTI_PAC"	DOUBLE PRECISION,
"OC_PAGAMENTI_COESIONE"	DOUBLE PRECISION,
"OC_DATA_INIZIO_PROGETTO"	DATE,
"OC_DATA_FINE_PROGETTO_PREVISTA"	DATE,
"OC_DATA_FINE_PROGETTO_EFFETTIVA"	DATE,
"DATA_INIZIO_PREV_STUDIO_FATT"	DATE,
"DATA_INIZIO_EFF_STUDIO_FATT"	DATE,
"DATA_FINE_PREV_STUDIO_FATT"	DATE,
"DATA_FINE_EFF_STUDIO_FATT"	DATE,
"DATA_INIZIO_PREV_PROG_PREL"	DATE,
"DATA_INIZIO_EFF_PROG_PREL"	DATE,
"DATA_FINE_PREV_PROG_PREL"	DATE,
"DATA_FINE_EFF_PROG_PREL"	DATE,
"DATA_INIZIO_PREV_PROG_DEF"	DATE,
"DATA_INIZIO_EFF_PROG_DEF"	DATE,
"DATA_FINE_PREV_PROG_DEF"	DATE,
"DATA_FINE_EFF_PROG_DEF"	DATE,
"DATA_INIZIO_PREV_PROG_ESEC"	DATE,
"DATA_INIZIO_EFF_PROG_ESEC"	DATE,
"DATA_FINE_PREV_PROG_ESEC"	DATE,
"DATA_FINE_EFF_PROG_ESEC"	DATE,
"DATA_INIZIO_PREV_AGG_BANDO"	DATE,
"DATA_INIZIO_EFF_AGG_BANDO"	DATE,
"DATA_FINE_PREV_AGG_BANDO"	DATE,
"DATA_FINE_EFF_AGG_BANDO"	DATE,
"DATA_INIZIO_PREV_STIP_ATTRIB"	DATE,
"DATA_INIZIO_EFF_STIP_ATTRIB"	DATE,
"DATA_FINE_PREV_STIP_ATTRIB"	DATE,
"DATA_FINE_EFF_STIP_ATTRIB"	DATE,
"DATA_INIZIO_PREV_ESECUZIONE"	DATE,
"DATA_INIZIO_EFF_ESECUZIONE"	DATE,
"DATA_FINE_PREV_ESECUZIONE"	DATE,
"DATA_FINE_EFF_ESECUZIONE"	DATE,
"DATA_INIZIO_PREV_COLLAUDO"	DATE,
"DATA_INIZIO_EFF_COLLAUDO"	DATE,
"DATA_FINE_PREV_COLLAUDO"	DATE,
"DATA_FINE_EFF_COLLAUDO"	DATE,
"OC_STATO_FINANZIARIO"	VARCHAR(255),
"OC_STATO_PROGETTO"	VARCHAR(255),
"OC_STATO_PROCEDURALE"	VARCHAR(255),
"OC_COD_FASE_CORRENTE"	VARCHAR(255),
"OC_DESCR_FASE_CORRENTE"	VARCHAR(255),
"COD_PROCED_ATTIVAZIONE"	VARCHAR(255),
"DESCR_PROCED_ATTIVAZIONE"	TEXT,
"COD_TIPO_PROCED_ATTIVAZIONE"	DOUBLE PRECISION,
"DESCR_TIPO_PROCED_ATTIVAZIONE"	VARCHAR(255),
"OC_CODFISC_PROGRAMMATORE"	VARCHAR(255),
"OC_DENOM_PROGRAMMATORE"	TEXT,
"OC_COD_FORMA_GIU_PROGRAMMATORE"	VARCHAR(255),
"OC_DESCR_FORMA_GIU_PROGRAMMATORE"	TEXT,
"OC_TOTALE_PROGRAMMATORI"	DOUBLE PRECISION,
"OC_CODFISC_ATTUATORE"	VARCHAR(255),
"OC_DENOM_ATTUATORE"	TEXT,
"OC_COD_FORMA_GIU_ATTUATORE"	VARCHAR(255),
"OC_DESCR_FORMA_GIU_ATTUATORE"	TEXT,
"OC_TOTALE_ATTUATORI"	DOUBLE PRECISION,
"OC_CODFISC_BENEFICIARIO"	VARCHAR(255),
"OC_DENOM_BENEFICIARIO"	TEXT,
"OC_COD_FORMA_GIU_BENEFICIARIO"	VARCHAR(255),
"OC_DESCR_FORMA_GIU_BENEFICIARIO"	TEXT,
"OC_TOTALE_BENEFICIARI"	DOUBLE PRECISION,
"OC_CODFISC_REALIZZATORE"	VARCHAR(255),
"OC_DENOM_REALIZZATORE"	TEXT,
"OC_COD_FORMA_GIU_REALIZZATORE"	VARCHAR(255),
"OC_DESCR_FORMA_GIU_REALIZZATORE"	TEXT,
"OC_TOTALE_REALIZZATORI"	DOUBLE PRECISION,
"OC_TOTALE_INDICATORI"	DOUBLE PRECISION,
"COD_INDICATORE_1"	VARCHAR(255),
"DESCR_INDICATORE_1"	TEXT,
"UNITA_MISURA_INDICATORE_1"	TEXT,
"PROGRAMMATO_INDICATORE_1"	DOUBLE PRECISION,
"REALIZZATO_INDICATORE_1"	DOUBLE PRECISION,
"COD_INDICATORE_2"	VARCHAR(255),
"DESCR_INDICATORE_2"	TEXT,
"UNITA_MISURA_INDICATORE_2"	TEXT,
"PROGRAMMATO_INDICATORE_2"	DOUBLE PRECISION,
"REALIZZATO_INDICATORE_2"	DOUBLE PRECISION,
"COD_INDICATORE_3"	VARCHAR(255),
"DESCR_INDICATORE_3"	TEXT,
"UNITA_MISURA_INDICATORE_3"	TEXT,
"PROGRAMMATO_INDICATORE_3"	DOUBLE PRECISION,
"REALIZZATO_INDICATORE_3"	DOUBLE PRECISION,
"COD_INDICATORE_4"	VARCHAR(255),
"DESCR_INDICATORE_4"	TEXT,
"UNITA_MISURA_INDICATORE_4"	TEXT,
"PROGRAMMATO_INDICATORE_4"	DOUBLE PRECISION,
"REALIZZATO_INDICATORE_4"	DOUBLE PRECISION,
"OC_FLAG_REGIONE_UNICA"	DOUBLE PRECISION,
"OC_FLAG_VISUALIZZAZIONE"	DOUBLE PRECISION,
"OC_FLAG_PAC"	DOUBLE PRECISION,
"OC_FLAG_CUP"	DOUBLE PRECISION,
"DATA_AGGIORNAMENTO"	DATE
);'''

map_fields = {
    #"ID":	"TEXT",
    "COD_LOCALE_PROGETTO":	"TEXT",
    "CUP":	"TEXT",
    "OC_TITOLO_PROGETTO":	"TEXT",
    "OC_SINTESI_PROGETTO":	"TEXT",
    "OC_LINK":	"TEXT",
    "OC_COD_CICLO":	"NUM",
    "OC_DESCR_CICLO":	"TEXT",
    "OC_COD_TEMA_SINTETICO":	"TEXT",
    "OC_TEMA_SINTETICO":	"TEXT",
    "COD_GRANDE_PROGETTO":	"TEXT",
    "DESCRIZIONE_GRANDE_PROGETTO":	"TEXT",
    "OC_COD_FONTE":	"TEXT",
    "OC_DESCR_FONTE":	"TEXT",
    "FONDO_COMUNITARIO":	"TEXT",
    "OC_CODICE_PROGRAMMA":	"TEXT",
    "OC_DESCRIZIONE_PROGRAMMA":	"TEXT",
    "COD_OB_TEMATICO":	"TEXT",
    "DESCR_OB_TEMATICO":	"TEXT",
    "COD_PRIORITA_INVEST":	"TEXT",
    "DESCR_PRIORITA_INVEST":	"TEXT",
    "OC_COD_CATEGORIA_SPESA":	"TEXT",
    "OC_DESCR_CATEGORIA_SPESA":	"TEXT",
    "OC_ARTICOLAZIONE_PROGRAMMA":	"TEXT",
    "OC_SUBARTICOLAZIONE_PROGRAMMA":	"TEXT",
    "OC_COD_ARTICOLAZ_PROGRAMMA":	"TEXT",
    "OC_DESCR_ARTICOLAZ_PROGRAMMA":	"TEXT",
    "OC_COD_SUBARTICOLAZ_PROGRAMMA":	"TEXT",
    "OC_DESCR_SUBARTICOLAZ_PROGRAMMA":	"TEXT",
    "COD_STRUMENTO":	"TEXT",
    "DESCR_STRUMENTO":	"TEXT",
    "DESCR_TIPO_STRUMENTO":	"TEXT",
    "CUP_COD_NATURA":	"TEXT",
    "CUP_DESCR_NATURA":	"TEXT",
    "CUP_COD_TIPOLOGIA":	"TEXT",
    "CUP_DESCR_TIPOLOGIA":	"TEXT",
    "CUP_COD_SETTORE":	"TEXT",
    "CUP_DESCR_SETTORE":	"TEXT",
    "CUP_COD_SOTTOSETTORE":	"TEXT",
    "CUP_DESCR_SOTTOSETTORE":	"TEXT",
    "CUP_COD_CATEGORIA":	"TEXT",
    "CUP_DESCR_CATEGORIA":	"TEXT",
    "COD_ATECO":	"TEXT",
    "DESCRIZIONE_ATECO":	"TEXT",
    "OC_COD_TIPO_AIUTO":	"TEXT",
    "OC_DESCR_TIPO_AIUTO":	"TEXT",
    "COD_REGIONE":	"TEXT",
    "DEN_REGIONE":	"TEXT",
    "COD_PROVINCIA":	"TEXT",
    "DEN_PROVINCIA":	"TEXT",
    "COD_COMUNE":	"TEXT",
    "DEN_COMUNE":	"TEXT",
    "OC_MACROAREA":	"TEXT",
    "OC_COD_SLL":	"NUM",
    "OC_DENOMINAZIONE_SLL":	"TEXT",
    "FINANZ_UE":	"NUM",
    "FINANZ_UE_FESR":	"NUM",
    "FINANZ_UE_FSE":	"NUM",
    "FINANZ_UE_FEASR":	"NUM",
    "FINANZ_UE_FEAMP":	"NUM",
    "FINANZ_UE_IOG":	"NUM",
    "FINANZ_STATO_FONDO_DI_ROTAZIONE":	"NUM",
    "FINANZ_STATO_FSC":	"NUM",
    "FINANZ_STATO_PAC":	"NUM",
    "FINANZ_STATO_COMPLETAMENTI":	"NUM",
    "FINANZ_STATO_ALTRI_PROVVEDIMENTI":	"NUM",
    "FINANZ_REGIONE":	"NUM",
    "FINANZ_PROVINCIA":	"NUM",
    "FINANZ_COMUNE":	"NUM",
    "FINANZ_RISORSE_LIBERATE":	"NUM",
    "FINANZ_ALTRO_PUBBLICO":	"NUM",
    "FINANZ_STATO_ESTERO":	"NUM",
    "FINANZ_PRIVATO":	"NUM",
    "FINANZ_DA_REPERIRE":	"NUM",
    "FINANZ_TOTALE_PUBBLICO":	"NUM",
    "ECONOMIE_TOTALI":	"NUM",
    "ECONOMIE_TOTALI_PUBBLICHE":	"NUM",
    "OC_FINANZ_UE_NETTO":	"NUM",
    "OC_FINANZ_UE_FESR_NETTO":	"NUM",
    "OC_FINANZ_UE_FSE_NETTO":	"NUM",
    "OC_FINANZ_UE_FEASR_NETTO":	"NUM",
    "OC_FINANZ_UE_FEAMP_NETTO":	"NUM",
    "OC_FINANZ_UE_IOG_NETTO":	"NUM",
    "OC_FINANZ_STATO_FONDO_ROT_NETTO":	"NUM",
    "OC_FINANZ_STATO_FSC_NETTO":	"NUM",
    "OC_FINANZ_STATO_PAC_NETTO":	"NUM",
    "OC_FINANZ_STATO_COMPL_NETTO":	"NUM",
    "OC_FINANZ_STATO_ALTRI_PROV_NETTO":	"NUM",
    "OC_FINANZ_REGIONE_NETTO":	"NUM",
    "OC_FINANZ_PROVINCIA_NETTO":	"NUM",
    "OC_FINANZ_COMUNE_NETTO":	"NUM",
    "OC_FINANZ_RISORSE_LIBERATE_NETTO":	"NUM",
    "OC_FINANZ_ALTRO_PUBBLICO_NETTO":	"NUM",
    "OC_FINANZ_STATO_ESTERO_NETTO":	"NUM",
    "OC_FINANZ_PRIVATO_NETTO":	"NUM",
    "OC_FINANZ_TOT_PUB_NETTO":	"NUM",
    "OC_COSTO_COESIONE":	"NUM",
    "IMPEGNI":	"NUM",
    "OC_IMPEGNI_GIURID_VINCOLANTI":	"NUM",
    "OC_IMPEGNI_TRASFERIMENTI":	"NUM",
    "OC_IMPEGNI_COESIONE":	"NUM",
    "TOT_PAGAMENTI":	"NUM",
    "OC_TOT_PAGAMENTI_BENEFICIARI":	"NUM",
    "OC_TOT_PAGAMENTI_TRASFERIMENTI":	"NUM",
    "COSTO_REALIZZATO":	"NUM",
    "COSTO_RENDICONTABILE_UE":	"NUM",
    "OC_TOT_PAGAMENTI_RENDICONTAB_UE":	"NUM",
    "OC_TOT_PAGAMENTI_FSC":	"NUM",
    "OC_TOT_PAGAMENTI_PAC":	"NUM",
    "OC_PAGAMENTI_COESIONE":	"NUM",
    "OC_DATA_INIZIO_PROGETTO":	"DATE",
    "OC_DATA_FINE_PROGETTO_PREVISTA":	"DATE",
    "OC_DATA_FINE_PROGETTO_EFFETTIVA":	"DATE",
    "DATA_INIZIO_PREV_STUDIO_FATT":	"DATE",
    "DATA_INIZIO_EFF_STUDIO_FATT":	"DATE",
    "DATA_FINE_PREV_STUDIO_FATT":	"DATE",
    "DATA_FINE_EFF_STUDIO_FATT":	"DATE",
    "DATA_INIZIO_PREV_PROG_PREL":	"DATE",
    "DATA_INIZIO_EFF_PROG_PREL":	"DATE",
    "DATA_FINE_PREV_PROG_PREL":	"DATE",
    "DATA_FINE_EFF_PROG_PREL":	"DATE",
    "DATA_INIZIO_PREV_PROG_DEF":	"DATE",
    "DATA_INIZIO_EFF_PROG_DEF":	"DATE",
    "DATA_FINE_PREV_PROG_DEF":	"DATE",
    "DATA_FINE_EFF_PROG_DEF":	"DATE",
    "DATA_INIZIO_PREV_PROG_ESEC":	"DATE",
    "DATA_INIZIO_EFF_PROG_ESEC":	"DATE",
    "DATA_FINE_PREV_PROG_ESEC":	"DATE",
    "DATA_FINE_EFF_PROG_ESEC":	"DATE",
    "DATA_INIZIO_PREV_AGG_BANDO":	"DATE",
    "DATA_INIZIO_EFF_AGG_BANDO":	"DATE",
    "DATA_FINE_PREV_AGG_BANDO":	"DATE",
    "DATA_FINE_EFF_AGG_BANDO":	"DATE",
    "DATA_INIZIO_PREV_STIP_ATTRIB":	"DATE",
    "DATA_INIZIO_EFF_STIP_ATTRIB":	"DATE",
    "DATA_FINE_PREV_STIP_ATTRIB":	"DATE",
    "DATA_FINE_EFF_STIP_ATTRIB":	"DATE",
    "DATA_INIZIO_PREV_ESECUZIONE":	"DATE",
    "DATA_INIZIO_EFF_ESECUZIONE":	"DATE",
    "DATA_FINE_PREV_ESECUZIONE":	"DATE",
    "DATA_FINE_EFF_ESECUZIONE":	"DATE",
    "DATA_INIZIO_PREV_COLLAUDO":	"DATE",
    "DATA_INIZIO_EFF_COLLAUDO":	"DATE",
    "DATA_FINE_PREV_COLLAUDO":	"DATE",
    "DATA_FINE_EFF_COLLAUDO":	"DATE",
    "OC_STATO_FINANZIARIO":	"TEXT",
    "OC_STATO_PROGETTO":	"TEXT",
    "OC_STATO_PROCEDURALE":	"TEXT",
    "OC_COD_FASE_CORRENTE":	"TEXT",
    "OC_DESCR_FASE_CORRENTE":	"TEXT",
    "COD_PROCED_ATTIVAZIONE":	"TEXT",
    "DESCR_PROCED_ATTIVAZIONE":	"TEXT",
    "COD_TIPO_PROCED_ATTIVAZIONE":	"NUM",
    "DESCR_TIPO_PROCED_ATTIVAZIONE":	"TEXT",
    "OC_CODFISC_PROGRAMMATORE":	"TEXT",
    "OC_DENOM_PROGRAMMATORE":	"TEXT",
    "OC_COD_FORMA_GIU_PROGRAMMATORE":	"TEXT",
    "OC_DESCR_FORMA_GIU_PROGRAMMATORE":	"TEXT",
    "OC_TOTALE_PROGRAMMATORI":	"NUM",
    "OC_CODFISC_ATTUATORE":	"TEXT",
    "OC_DENOM_ATTUATORE":	"TEXT",
    "OC_COD_FORMA_GIU_ATTUATORE":	"TEXT",
    "OC_DESCR_FORMA_GIU_ATTUATORE":	"TEXT",
    "OC_TOTALE_ATTUATORI":	"NUM",
    "OC_CODFISC_BENEFICIARIO":	"TEXT",
    "OC_DENOM_BENEFICIARIO":	"TEXT",
    "OC_COD_FORMA_GIU_BENEFICIARIO":	"TEXT",
    "OC_DESCR_FORMA_GIU_BENEFICIARIO":	"TEXT",
    "OC_TOTALE_BENEFICIARI":	"NUM",
    "OC_CODFISC_REALIZZATORE":	"TEXT",
    "OC_DENOM_REALIZZATORE":	"TEXT",
    "OC_COD_FORMA_GIU_REALIZZATORE":	"TEXT",
    "OC_DESCR_FORMA_GIU_REALIZZATORE":	"TEXT",
    "OC_TOTALE_REALIZZATORI":	"NUM",
    "OC_TOTALE_INDICATORI":	"NUM",
    "COD_INDICATORE_1":	"TEXT",
    "DESCR_INDICATORE_1":	"TEXT",
    "UNITA_MISURA_INDICATORE_1":	"TEXT",
    "PROGRAMMATO_INDICATORE_1":	"NUM",
    "REALIZZATO_INDICATORE_1":	"NUM",
    "COD_INDICATORE_2":	"TEXT",
    "DESCR_INDICATORE_2":	"TEXT",
    "UNITA_MISURA_INDICATORE_2":	"TEXT",
    "PROGRAMMATO_INDICATORE_2":	"NUM",
    "REALIZZATO_INDICATORE_2":	"NUM",
    "COD_INDICATORE_3":	"TEXT",
    "DESCR_INDICATORE_3":	"TEXT",
    "UNITA_MISURA_INDICATORE_3":	"TEXT",
    "PROGRAMMATO_INDICATORE_3":	"NUM",
    "REALIZZATO_INDICATORE_3":	"NUM",
    "COD_INDICATORE_4":	"TEXT",
    "DESCR_INDICATORE_4":	"TEXT",
    "UNITA_MISURA_INDICATORE_4":	"TEXT",
    "PROGRAMMATO_INDICATORE_4":	"NUM",
    "REALIZZATO_INDICATORE_4":	"NUM",
    "OC_FLAG_REGIONE_UNICA":	"NUM",
    "OC_FLAG_VISUALIZZAZIONE":	"NUM",
    "OC_FLAG_PAC":	"NUM",
    "OC_FLAG_CUP":	"NUM",
}

def main(args, password=None):
    with open(args.csvfile, newline='', encoding='utf-8-sig', mode='r') as f:
        reader = csv.DictReader(f, delimiter=';', quotechar='"')
        qry_preamble = f'INSERT INTO {args.table}('
        qry_end = ");"

        host = f' host={args.dbhost}' if args.dbhost else ''
        port = f' port={args.port}' if args.port else ''
        user = f' user={args.user}' if args.user else ''
        password = f' password={password}' if password else ''
        with psycopg.connect(f"dbname={args.dbname}{host}{user}{password}") as conn:
            cur = conn.cursor()
            if args.delete:
                try:
                    cur.execute(f"DROP TABLE {args.table};")
                    conn.commit()
                except psycopg.errors.UndefinedTable:
                    conn.rollback()
                
            try:
                qry = f'SELECT * FROM {args.table} LIMIT 1;'
                cur.execute(qry)
            except psycopg.errors.UndefinedTable:
                conn.rollback()
                qry = sql_create.format(args.table)
                cur.execute(qry)
                conn.commit()
        
            try:
                rows = []
                for row in reader:
                    rcd_dict = {}
                    for fld in map_fields:
                        if map_fields[fld] == "TEXT":
                            rcd_dict[fld] = row[fld] if row[fld] else None
                        elif map_fields[fld] == "NUM":
                            rcd_dict[fld] = float(row[fld].replace(',', '.')) if row[fld] else None
                        elif map_fields[fld] == "DATE":
                            rcd_dict[fld] = datetime.date.strptime(row[fld], '%Y%m%d') if row[fld] else None
                    rows.append(rcd_dict)
                qry = f'{qry_preamble}{", ".join([f'"{k}"' for k in map_fields])}) VALUES ({", ".join([f"%({k})s" for k in rcd_dict])});'
                cur.executemany(qry, rows)
                conn.commit()
                
                    
            except csv.Error as e:
                sys.exit(f'file {filename}, line {reader.line_num}: {e}')
            except psycopg.Error as e:
                print(qry, rcd_dict)
                sys.exit(f'line {reader.line_num}: {e}')    
    return 0


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("csvfile", help="File csv ottenuto da Opencoesione")
    parser.add_argument("dbname", help="Database in cui importarei dati", default='opencoesione')
    parser.add_argument("-H", "--dbhost", help="Host postgresql")
    parser.add_argument("-P", "--port", help="Porta, default=5432", default='5432', type=int)
    parser.add_argument("-u", "--user", help="Username postgresql")
    parser.add_argument("-p", "--password", help="Password postgresql richiesta", action='store_true')
    parser.add_argument("-t", "--table", help="Tabella in cui inserire i dati", default='opencoesione')
    parser.add_argument("-d", "--delete", help="Elimina e ricrea la tabella", action='store_true')
    
    args = parser.parse_args()
    
    psw = None
    if args.password:
        import getpass
        psw = getpass.getpass()
        
    sys.exit(main(args, password=psw))
